### PR TITLE
陳佳欣/Jessie Chen-Guide - Part4

### PR DESCRIPTION
**Pull request by stella0320**
彭彭你好:

這是本周的任務，網址如下，謝謝

http://34.214.175.62:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
If we scroll down and up quickly, your code will load the same page multiple times.

未命名-15

**Comment by stella0320** [comment]
Hi 彭彭，我修改了一版，請再確認，謝謝

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Comment by stella0320** [comment]
Hi 彭彭
我發了re-quest 囉！再麻煩你了！謝謝

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your page load nothing at start.

**Comment by stella0320** [comment]
Sorry... 沒注意到360px 寬度的網頁會有問題，有重新修改了

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by stella0320** [comment]
彭彭你好:

這是本周的任務，網址如下，謝謝

http://34.214.175.62:3000/
http://34.214.175.62:3000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Color of separating lines should be ligher.
2. More spacing on the top of second separating line.
3. 新台幣2000元 is too small.

Next time, you should merge pull request after review approval.

**Comment by stella0320** [comment]
彭彭你好:

已經有修改了，謝謝提醒!

**Review by cwpeng — CHANGES_REQUESTED** [review]
Second separating line is 2px height still.

**Comment by stella0320** [comment]
彭彭你好:

已經有修改了，謝謝提醒!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by stella0320** [comment]
彭彭你好:

這是本周的任務，網址如下，謝謝

http://34.214.175.62:3000/
http://34.214.175.62:3000/attraction/1

**Review by cwpeng — CHANGES_REQUESTED** [review]
Only when users click on 登入/註冊, we show sign in/sign up dialog for them.

**Comment by stella0320** [comment]
彭彭你好: 已修正，謝謝提醒

**Review by cwpeng — APPROVED** [review]
OK. Done.

We have to merge pull request after review approval. If you don't know why we have to do this and what the thinking behind these actions on GitHub, try to figure it out.

**Pull request merged**
